name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-tests:
    name: API - Instalação e Healthcheck
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-site/api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependências
        run: |
          npm install --no-audit --no-fund

      - name: Iniciar API em background
        run: |
          node server.js &
          echo $! > api.pid
          sleep 2

      - name: Testar endpoint /health com retries
        run: |
          for i in {1..10}; do
            if curl -sf http://localhost:3000/health > /dev/null; then
              echo "API saudável"; exit 0; fi; echo "Aguardando API..."; sleep 2; done
          echo "API não respondeu a tempo"; exit 1

      - name: Encerrar API
        if: always()
        run: |
          if [ -f api.pid ]; then kill $(cat api.pid) || true; fi

  docker-build:
    name: Docker - Build da imagem
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-site
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Build
        run: docker build -t academia-dashboard:test .

  compose-validate:
    name: Docker Compose - Validação
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-site
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validar docker-compose.yml
        run: docker compose -f docker-compose.yml config
      - name: Validar docker-compose.prod.yml
        run: docker compose -f docker-compose.prod.yml config

  terraform-validate:
    name: Terraform - Fmt e Validate (sem backend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-site/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: terraform fmt -check
        run: terraform fmt -check -recursive
      - name: terraform init (backend local)
        run: terraform init -backend=false -input=false
      - name: terraform validate
        run: terraform validate -no-color





